TESTLINK_PRJ: syz-

QA12_ODIN:
  API_KEY: NWULY5lMmYwvInPV4P5a5sKFz5cPapH0SwS9f5dmPa4feNbTYorOzdeUKkCJg0mG
  PARTNER_ID: 353738
STD1_ODIN:
  API_KEY: EIhEBzyV1Szfbxup1uZ69mLNNidDMxICEHQhaRtQP4LTtagYq4433iYUNVgijIbF
  PARTNER_ID: 355358
STD2_ODIN:
  API_KEY: uLlOlGXJ9hYXKdQHy0538PjJxPc853YhFwSAJ8PrusAP6t8XxHe8G8x3WbVizunw
  PARTNER_ID: 371613
PROD_ODIN:
  API_KEY: s2Fz4VywMJ8l7pFJvTMqiBif3uVlSEsDTEU42MGlIUlapDZG1iFr4GGkhDDQYIqd
  PARTNER_ID: 357228