ACTIVATE: keyless
BUILD: 665
CREDENTIAL: null
DATABASE_ENABLED: false
DAY: null
DAYOFWEEK: null
DRY_RUN: false
END_DATE: null
ENVIRONMENT: QA12
FEATURES: features/winfryr
HOUR: null
JOB: null
LANGUAGE: null
MINUTE: null
MONTH: null
OEM_CLIENT: mozypro
PRODUCT: WINFRYR
RERUN: false
RUN_BY: clientqaautomation@emc.com
SCHEDULE: null
SECOND: null
START_DATE: null
TAGS: '@Winfryr-111'
TASKID: null
TESTRUN: WINFRYR_MOZYPRO_QA12_2017_12_08T09_01_15Z
WAITDAYS: null
WAITHOURS: null
WAITMINUTES: null
WAITSECONDS: null
WAITWEEKS: null
WEEK: null
YEAR: null
